language: python

cache: pip

services:
  - redis-server

python:
  - "3.5"

install:
  - pip install -e .
  - pip install -r tests/requirements.txt

script:
  - flake8 arq/ tests/
  - py.test --cov=arq

after_success:
  - codecov
